# Generated by Django 3.2.16 on 2023-01-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_confirmed_booking_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirm',
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
