# Generated by Django 3.2.16 on 2023-01-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230129_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='sp_occasion',
            new_name='special_occasion',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='sp_requirements',
            new_name='special_requirements',
        ),
    ]
