# Generated by Django 3.2.16 on 2023-01-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230129_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DessertMenu',
            new_name='Dessert',
        ),
        migrations.RenameModel(
            old_name='MainsMenu',
            new_name='Mains',
        ),
    ]
