# Generated by Django 3.2.16 on 2023-01-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20230129_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mains',
            new_name='Main',
        ),
    ]
